### ISSUE TITLE
Can you provide requirment.txt to explain what dependencies pyforce need?

### ISSUE THREAD

**Issue by zrq1706** [ERMETE-Lab/ROSE-pyforce#2]

**Comment by zrq1706** [comment]
I see it in https://ermete-lab.github.io/ROSE-pyforce/intro.html.

**Comment by Steriva** [comment]
A requirements.txt file has been added in https://github.com/ERMETE-Lab/ROSE-pyforce/blob/main/pyforce/requirements.txt

Be aware that dolfinx cannot be installed using pip, conda is required.
The installation notes are available in the documentation.
