### ISSUE TITLE
License file with incomplete authors

### ISSUE THREAD

**Issue by alberto743** [ERMETE-Lab/ROSE-pyforce#6]
License is MIT, but the authors provided in the heading of the license file is inconsistent.
I guess that instead of "Copyright (c) 2024 ROSE-pyforce", there should be something like "Copyright (c) 2024 Politecnico di Milano, Italy".

**Comment by alberto743** [comment]
It should be noted that this information is later available in the `__init__.py` file and in the heading of each source.

**Comment by Steriva** [comment]
I have updated the license, after having discussed with the other contributors from Polimi.
